/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package generics

import generics.payloads.AHSPayload
import generics.payloads.DigitalPayload
import generics.payloads.StringPayload
import generics.processors.OutputProcessor

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun example() {
    val tasks = arrayOf(
        Task<AHSPayload>(AHSPayload("some AHS data")),
        Task<DigitalPayload>(DigitalPayload("some digital data")),
        Task<StringPayload>(StringPayload("some string data"))
    )

    val processor = OutputProcessor()

    for (task in tasks) {
        processor.processTask(task)
    }
}

fun main() {
    println(App().greeting)

    example()
}
