/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>

#include "Task.h"
#include "TaskId.h"
#include "TaskController.h"
#include "app.h"

std::string task_scheduler::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    TaskId id("task-for-demonstration");
    Task newTask(id);
    newTask.setNumShots(12345);

    TaskController &controller = TaskController::getInstance();

    controller.acceptTask(newTask);

    std::cout << "Accepted task" << std::endl;

    return 0;
}
