/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>

#include "InMemoryTaskPersistenceManager.h"
#include "Shot.h"
#include "ShotController.h"
#include "Task.h"
#include "TaskId.h"
#include "TaskController.h"
#include "TaskPersistenceManagerFactory.h"
#include "app.h"

std::string task_scheduler::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    InMemoryTaskPersistenceManager persistenceMgr;
    TaskPersistenceManagerFactory::setTaskPersistenceManager(&persistenceMgr);

    TaskId id("task-for-demonstration");
    Task newTask(id);
    newTask.setNumShots(12345);

    TaskController &taskController = TaskController::getInstance();

    taskController.acceptTask(newTask);

    std::cout << "Accepted task" << std::endl;

    ShotController &shotController = ShotController::getInstance();

    Shot* nextShot = shotController.getNextShot();

    std::cout << "Retrieved shot" << std::endl;

    delete nextShot;

    return 0;
}
